config/routes.rb
Rails.application.routes.draw do
  resources :qsheets
=begin
  resources :users, only: [:new, :create] do
    member do
      get :activate
    end
  end
=end

  resources :reset_passwords, only: [:new, :create, :update, :edit]
  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin_setup do
    resources :contest, only: [:new, :create, :destroy, :edit, :show]
    resources :judge, only: [:new, :create, :destroy, :edit, :show]
    resources :auctioneer, only: [:new, :create, :destroy, :edit, :show]
    resources :question, only: [:new, :create, :destroy, :edit, :show]
  end
  get 'admin_setup' => 'admin_setup#setup'
  get 'admin_judge' => 'admin#judge'
  get 'admin_auctioneer' => 'admin#auctioneer'
  get 'admin_contest' => 'admin#contest'
  
  resources :admin, only: [:index, :judge, :auctioneer, :contest, :new, :create, :scoreSummary]
  resources :judge, only: [:index, :edit, :update, :show]

  get 'judge_score' => 'judge#score'
  get 'admin_scoreSummary' => 'admin#scoreSummary'
  
  get 'qsheets_show' => 'qsheets#show'

  
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out

  root to: 'main#index'

end

app/models/qsheet.rb
class Qsheet < ActiveRecord::Base
    has_many :questions
    belongs_to :division
    accepts_nested_attributes_for :questions
end

app/controllers/qsheets_controller.rb
class QsheetsController < ApplicationController
  before_action :set_qsheet, only: [:show, :edit, :update, :destroy]

  # GET /qsheets
  # GET /qsheets.json
  def index
    if current_user.user_type == 'Admin'
      @qsheets = Qsheet.all
      @contests = Contest.all
      @divisions = Division.all
    else 
      @@contest_id = Contest.find(Judge.find(current_user.id)).id
      _allDivisions = Division.find_by_contest_id(contest_id)
      _allDivisions.each do |currDiv|
        @qsheets = Qsheet.find_by_division_id(currDiv.id)
      end 
    end 
      
    
    # @currIndex = 0
  end

  # GET /qsheets/1
  # GET /qsheets/1.json
  def show
    @qsheet = Qsheet.find(params[:id]) # retrieve question ID from URI route
    # puts "About to use tsheet"
    # @tSheet = "Hello again"
    
  end

  # GET /qsheets/new
  def new
    @contest = Contest.find(params[:id])
    @qsheet = Qsheet.new
    2.times { @qsheet.questions.build }
  end

  # GET /qsheets/1/edit
  def edit
    @qsheet = Qsheet.find_by(:id => params[:id])
    @division = Division.find_by(:id => @qsheet.division_id)
    @contest = Contest.find_by(:id => @division.contest_id)
  end

  # POST /qsheets
  # POST /qsheets.json
  def create
    @qsheet = Qsheet.new(qsheet_params)
    #@contests = Contest.find(1)
    respond_to do |format|
      if @qsheet.save
        format.html { redirect_to @qsheet, notice: 'Qsheet was successfully created.' }
        format.json { render :show, id: @qsheet.id, status: :created, location: @qsheet }
      else
        format.html { render :new }
        format.json { render json: @qsheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qsheets/1
  # PATCH/PUT /qsheets/1.json
  def update
    @qsheet = Qsheet.find_by(:division_id => params[:id])
    respond_to do |format|
      if params[:qsheet] != nil
        save_questions(params[:qsheet][:questions_attributes], @qsheet.division_id)
      end
      
      format.html { redirect_to @qsheet, notice: 'Qsheet was successfully updated.' }
      format.json { render :show, status: :ok, location: @qsheet }
    end
  end

  # DELETE /qsheets/1
  # DELETE /qsheets/1.json
  def destroy
    @question = Question.find(params[:id])
    @scores = Scoresheet.where(:question_id => @question.id)
    @scores.each do |s|
      s.destroy
    end
    @question.destroy 
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Qsheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qsheet
      # @qsheet = Qsheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qsheet_params
      params.require(:qsheet).permit(:contest, :questions_attributes => [:id, :content, :dataType])
    end

    def save_questions(qs, division_id)
      if qs == nil
        return false
      end
      qs.each do |q|
        if q[1][:dataType] == "I" || q[1][:dataType] == "S"
          question = Question.new
          question.dataType = q[1][:dataType]
          question.content = q[1][:content]
          question.qsheet_id= Qsheet.find_by(:division_id => division_id).id
          if !question.save()
            return false
          end
  
          Auctioneer.where(:division_id => division_id).each do |auc|
            score = Scoresheet.new
            score.auctioneer_id = auc.id
            score.question_id = question.id
            score.judge_id = auc.judge_id
            score.score = "empty"
            if !score.save()
              return false
            end
          end
        end
      end
      return true
    end
end

app/helpers/qsheets_helper.rb
module QsheetsHelper
end

app/views/qsheets/_form.html.erb
<%= form_for(@qsheet, :html => {:class => 'form-horizontal'}) do |f| %>


<!--
  <div class="form-group">
      <%#= f.label :division, class: 'control-label col-sm-2' %>
    <div class="row">
    <div class="col-xs-6 col-sm-3">
        <a class="btn btn-primary btn-select">
            <input type="hidden" class="btn-select-input" id="" name="" value="" />
            <span class="btn-select-value">Select an Item</span>
            <span class='btn-select-arrow glyphicon glyphicon-chevron-down'></span>
            <ul>
                <% #divisions = Division.where(contest_id: @contest.id) %>
                <% #divisions.each do |division| %>
                    <li><%#= division.division_name + ": " + division.round.to_s %></li>
                <% #end %> 
            </ul>
        </a>
    </div>
</div>
  </div>
 -->
  
  <div class="form-group">
      <%= submit_tag "+ Add question", :type => 'button', :id => 'addQuestion', 
          :class => 'btn btn-primary btn-med',
          :onclick => 'addQuestionField()' %> 
  </div>
   
  <h2>Questions</h2>
   
  <div id="myList" class="form-group">
    <!--This is where the questions are added dynamically-->
  </div>
  
  <div class="form-group">
      <%= f.submit "DONE", class: "btn btn-primary btn-med" %>
  <div>
<% end %>


<script>

$(document).ready(function () {
    $(".btn-select").each(function (e) {
        document.getElementById("admin-nav").className = "active"
        var value = $(this).find("ul li.selected").html();
        if (value != undefined) {
            $(this).find(".btn-select-input").val(value);
            $(this).find(".btn-select-value").html(value);
        }
    });
});

$(document).on('click', '.btn-select', function (e) {
    e.preventDefault();
    var ul = $(this).find("ul");
    if ($(this).hasClass("active")) {
        if (ul.find("li").is(e.target)) {
            var target = $(e.target);
            target.addClass("selected").siblings().removeClass("selected");
            var value = target.html();
            $(this).find(".btn-select-input").val(value);
            $(this).find(".btn-select-value").html(value);
        }
        ul.hide();
        $(this).removeClass("active");
    }
    else {
        $('.btn-select').not(this).each(function () {
            $(this).removeClass("active").find("ul").hide();
        });
        ul.slideDown(300);
        $(this).addClass("active");
    }
});

$(document).on('click', function (e) {
    var target = $(e.target).closest(".btn-select");
    if (!target.length) {
        $(".btn-select").removeClass("active").find("ul").hide();
    }
});

</script>

app/views/qsheets/_showQuestion.html.erb
<% @counter = 0 %>
<% @questionIDArray = Question.where(qsheet_id: @qsheet.id).pluck(:id) %>
<table class="table table-striped">
    <thead class="thead-inverse">
        <tr>
            <th colspan="4">
                <% @corrDivision = Division.find(@qsheet.division_id) %>
                  <%= @corrContest = Contest.find(@corrDivision.contest_id).contest_name %> Questions
                  <br>
                  Division: <%= @corrDivision.division_name %>, Round 
                  <%= @corrDivision.round %>
            </th>
        </tr>
    </thead>
    <thead>
        <tr>
            <th>Number</th>
            <th>Integer (I) or String (S)?</th>
            <th>Question</th>
            <th>Delete</th>
        </tr>
    </thead>
    
    <tbody>
    <% @questionIDArray.each do |id| %>
    <% @currQuestion = Question.find(id) %>
        <tr>
            <td><%= @counter += 1 %></td>
            <td><%= @currQuestion.dataType%></td>
            <td><%= @currQuestion.content %></td>
            <td><%= link_to 'Delete', qsheet_path(:id => id), :method => :delete %></td>
        </tr>
    <% end %> 
    </tbody>
</table>


 

app/views/qsheets/edit.html.erb
<h1>Editing Qsheet for <%= @contest.contest_name + " " + @division.division_name + " " + @division.round.to_s %></h1>

<%= render 'form' %>

<%= link_to 'Show', @qsheet %> |
<%= link_to 'Back', qsheets_path %>

app/views/qsheets/index.html.erb
<p id="notice"><%= notice %></p>
<script>
  document.getElementById("admin-setup-nav").className = "active";
</script>

<ul class="nav nav-tabs">
    <li><%= link_to 'Contest', new_admin_setup_contest_path %></li>
    <li><%= link_to 'Judge', new_admin_setup_judge_path %></li>
    <li><%= link_to 'Auctioneer', new_admin_setup_auctioneer_path %></li>
    <li class='active'><%= link_to 'Questions', qsheets_path %></li>
</ul>


<% @contests.each do |contest| %>
<br>
  <h1 class="display-4"><%= contest.contest_name%> Contest</h1>
  <table class="table table-striped table-bordered">
    <thead class="thead-inverse">
      <tr>
        <th class="col-xs-6 col-sm-4">Division</th>
        <th class="col-xs-6 col-sm-4">Round No.</th>
        <th class="col-xs-6 col-sm-4">View</th>
      </tr>
    </thead>
    
    <tbody>
      <!--we are looking at a list of all qsheets
      every round has 1 qsheet
      fewere divisions than rounds
      for each division, if its contest id 
      matches the current contest id, we are good.-->
      <% @divisions.each do |division| %>
      <%   if division.contest_id == contest.id %> 
            <tr>
              <td><%= division.division_name %></td>
              <td><%= division.round %></td>
              <td>
                <%=  link_to qsheets_show_path(:id => division.id) do %> View questions
                    <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> 
                <% end %> 
              </td>
            </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/qsheets/new.html.erb
<ul class="nav nav-tabs">
    <li><%= link_to 'Contest', new_admin_setup_contest_path %></li>
    <li><%= link_to 'Judge', new_admin_setup_judge_path %></li>
    <li><%= link_to 'Auctioneer', new_admin_setup_auctioneer_path %></li>
    <li class='active'><%= link_to 'Questions', qsheets_path %></li>
</ul>

<%= link_to(qsheets_path, :html => {:class => 'btn btn-default btn-med'}) do %>
<span class='glyphicon glyphicon-chevron-left'>Back</span>
<% end %>

<h1>New Qsheet for <%= @contest.contest_name %></h1>

<%= render 'form' %>

app/views/qsheets/show.html.erb
<p id="notice"><%= notice %></p>
<script>
  document.getElementById("admin-setup-nav").className = "active";
</script>

<ul class="nav nav-tabs">
    <li><%= link_to 'Contest', new_admin_setup_contest_path %></li>
    <li><%= link_to 'Judge', new_admin_setup_judge_path %></li>
    <li><%= link_to 'Auctioneer', new_admin_setup_auctioneer_path %></li>
    <li class='active'><%= link_to 'Questions', qsheets_path %></li>
</ul>

<%= link_to '< Back to QSheets', qsheets_path %>

<%= render 'showQuestion' %>

<button class="btn btn-default btn-med pull-right">
  <%= link_to '+ Add New Questions', edit_qsheet_path(:id => @qsheet.division_id) %>
</button>