config/routes.rb
Rails.application.routes.draw do
  resources :qsheets
=begin
  resources :users, only: [:new, :create] do
    member do
      get :activate
    end
  end
=end

  resources :reset_passwords, only: [:new, :create, :update, :edit]
  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin_setup do
    resources :contest, only: [:new, :create, :destroy, :edit, :show]
    resources :judge, only: [:new, :create, :destroy, :edit, :show]
    resources :auctioneer, only: [:new, :create, :destroy, :edit, :show]
    resources :question, only: [:new, :create, :destroy, :edit, :show]
  end
  get 'admin_setup' => 'admin_setup#setup'
  get 'admin_judge' => 'admin#judge'
  get 'admin_auctioneer' => 'admin#auctioneer'
  get 'admin_contest' => 'admin#contest'
  
  resources :admin, only: [:index, :judge, :auctioneer, :contest, :new, :create, :scoreSummary]
  resources :judge, only: [:index, :edit, :update, :show]

  get 'judge_score' => 'judge#score'
  get 'admin_scoreSummary' => 'admin#scoreSummary'
  
  get 'qsheets_show' => 'qsheets#show'

  
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out

  root to: 'main#index'

end

app/views/admin/index.html.erb
<script>
  document.getElementById('admin-nav').className = "active"; 
</script>
<p><%= @allAucList %></p>

<% @contests.each do |contest| %>
    <h2>Results for: 
      <%= contest.contest_name%>
    </h2>
    <table class="table table-bordered table-striped">
        <thead class="thead-inverse">
            <th>Division</th>
            <th>Round</th>
            <th>Name</th>
            <th>Score</th>
            <th>View Results</th>
        </thead>
        
        <tbody>
            <% Division.where(contest_id: contest.id).each do |div| %>
                <% @aucList.each do |auc| %> 
                    <% tempAuc = Auctioneer.find_by(:user_id => auc.id) %>
                    <% if tempAuc.division_id == div.id #find auc by div%>
                        <tr>
                            <td><%= div.division_name %></td>
                            <td><%= div.round %></td>
                            <td><%= auc.name %></td>
                            <td><%= @aucAvgScore[tempAuc.id] %></td>
                            <td>
                              <%=  link_to admin_scoreSummary_path(:auc_id => tempAuc.id, :avgScore => @aucAvgScore[tempAuc.id], :contest_name => contest.contest_name) do %>See
                                  <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> 
                              <% end %> 
                            </td>
                        </tr>

                    <% end %> 
                <% end %> 
                <tr style="background-color: rgba(179, 204, 230,.25);"> <td> </td> <td> </td> <td> </td> <td> </td> <td> </td></tr>
            <% end %> 
        </tbody>
          
    </table>
    <br>
<% end %>
  



<script>

$(document).ready(function () {
    $(".btn-select").each(function (e) {
        document.getElementById("admin-nav").className = "active"
        var value = $(this).find("ul li.selected").html();
        if (value != undefined) {
            $(this).find(".btn-select-input").val(value);
            $(this).find(".btn-select-value").html(value);
        }
    });
});

$(document).on('click', '.btn-select', function (e) {
    e.preventDefault();
    var ul = $(this).find("ul");
    if ($(this).hasClass("active")) {
        if (ul.find("li").is(e.target)) {
            var target = $(e.target);
            target.addClass("selected").siblings().removeClass("selected");
            var value = target.html();
            $(this).find(".btn-select-input").val(value);
            $(this).find(".btn-select-value").html(value);
            document.getElementById("resultsTitle").innerText = 'Realtime Results - ' + value.toString();
            document.getElementById("judgeTitle").innerText = 'Judges - ' + value.toString();
        }
        ul.hide();
        $(this).removeClass("active");
    }
    else {
        $('.btn-select').not(this).each(function () {
            $(this).removeClass("active").find("ul").hide();
        });
        ul.slideDown(300);
        $(this).addClass("active");
    }
});

$(document).on('click', function (e) {
    var target = $(e.target).closest(".btn-select");
    if (!target.length) {
        $(".btn-select").removeClass("active").find("ul").hide();
    }
});

</script>

app/views/admin/scoreSummary.html.erb
<%= link_to admin_index_path do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    Back to Results
<% end %> 

<h1>Results for <%= @aucName %></h1>
<h3>
  Tournament: <%= @contestName %> 
</h3>
<h3>
  Division: <%= @divName %> 
</h3>
 <h3>
  Round: <%= @divRound %> 
</h3>
 <h3>
  Average Score: <%= @averageScore %>
</h3>
<br/>
<% @judgeHash.each do |key, lol_quad| %>
    <% @dataRow = 0 %>
    <table class="table table-bordered">
        <thead class="thead-inverse">
            <tr>
                <th colspan="4">
                    Scoresheet # <%= @scoresheetN += 1 %>  <br/>
                    Judged by: <%= lol_quad[ @scoresheetN-1][2] %>
                </th>
            </tr>
        </thead>
      <thead>
        <tr>
              <th>#</th>
              <th>Question</th>
              <th>Score</th>
              <th>Submitted</th>
        </tr>
      </thead>
      <tbody>
        <% lol_quad.each do |quad| %>
            <tr>
              <th scope="row"><%= @dataRow += 1 %></th>
              <td> <%= quad[0] %> </td>
              <td> <%= quad[1] %> </td>
              <td> <%= quad[3] %> </td>
            </tr>
        <% end %>
      </tbody>
    </table>
<% end %>
        
        
        

app/views/admin/show.html.erb
<script>
  document.getElementById("admin-nav").className = "active";
</script>

<div class="container">
  <h2>Welcome Admin! See the Current Judges Below</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Judge Name</th>
        <th>Judge Email</th>
        <th>Judge Password</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Mark Wahlber</td>
        <td>markyboy@gmail.com</td>
        <td>iThinkImSuperCool</td>
      </tr>
      <tr>
        <td>Will Ferrell</td>
        <td>MrFerrel@yahoo.com</td>
        <td>booYah12_12</td>
      </tr>
      <tr>
        <td>Billy Mars</td>
        <td>billLovesSeafood@gmail.com</td>
        <td>shrimpSmoothies</td>
      </tr>
    </tbody>
  </table>
</div>