config/routes.rb
Rails.application.routes.draw do
  resources :qsheets
=begin
  resources :users, only: [:new, :create] do
    member do
      get :activate
    end
  end
=end

  resources :reset_passwords, only: [:new, :create, :update, :edit]
  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin_setup do
    resources :contest, only: [:new, :create, :destroy, :edit, :show]
    resources :judge, only: [:new, :create, :destroy, :edit, :show]
    resources :auctioneer, only: [:new, :create, :destroy, :edit, :show]
    resources :question, only: [:new, :create, :destroy, :edit, :show]
  end
  get 'admin_setup' => 'admin_setup#setup'
  get 'admin_judge' => 'admin#judge'
  get 'admin_auctioneer' => 'admin#auctioneer'
  get 'admin_contest' => 'admin#contest'
  
  resources :admin, only: [:index, :judge, :auctioneer, :contest, :new, :create, :scoreSummary]
  resources :judge, only: [:index, :edit, :update, :show]

  get 'judge_score' => 'judge#score'
  get 'admin_scoreSummary' => 'admin#scoreSummary'
  
  get 'qsheets_show' => 'qsheets#show'

  
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out

  root to: 'main#index'

end

app/models/judge.rb
class Judge < ActiveRecord::Base
    belongs_to :user
    belongs_to :contests
end

app/controllers/admin/judge_controller.rb
# Aaron created this April 7 when trying to build results page.... NEEDS FIXES
class Admin::JudgeController < ApplicationController
    skip_before_action :require_login

    def new
        @user = User.new
        @member=User.where(user_type: "Judge")
    end

    def index
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        @user.user_type = "Judge"
      
        if @user.save
            flash[:success] = 'Successfully created a Judge'
        else
            flash[:success] = 'Failed to created a Judge'
        end
            redirect_to new_admin_setup_judge_path
    end

    def destroy
        @judge= User.find params[:id]
        @judge.destroy
        flash[:notice] = "Judge #{@judge.name} deleted"
        redirect_to new_admin_setup_judge_path
    end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end

end

app/controllers/admin_setup/judge_controller.rb
class AdminSetup::JudgeController < ApplicationController
    skip_before_action :require_login

    def new
        @user = User.new
        @new_judge = Judge.new
        @member = User.where(user_type: "Judge")
        @contest = Contest.new
        @judges = User.joins(:judges).pluck_to_hash(:contest_id)
        #@judges.each do |judge| Contest.where(:id => judge[:contest_id]).contest_name end
        
        @jList  = []
        contest_name = []
        @judges.each do |judge|
            @c = Contest.find_by(:id => judge[:contest_id])
            
            if @c != nil
                contest_name << @c.contest_name
            else
                contest_name << "-"
            end
        end
        
        i = 0
        @member.each do |member|
            mem = {}
            mem[:id] = member[:id]
            mem[:name] = member[:name]
            mem[:email] = member[:email]
            mem[:bare_password] = member[:bare_password]
            mem[:contest_name] = contest_name[i]
            i = i + 1
            @jList << mem
        end
        
    end

    def index
        @user = User.new
        @new_judge = Judge.new
        @contest = Contest.new
    end

    def create
        @user = User.new(user_params)
        @new_judge = Judge.new
        @contest = Contest.new
        
        puts params
        
        @user.user_type = "Judge"
        @user.bare_password = @user.password
        
        if @user.save
            flash[:success] = 'Successfully created a Judge'
            @new_judge.user_id = @user.id
            @new_judge.contest_id = params[:contest][:contest_name]
            @new_judge.save
        else
            flash[:success] = 'Failed to created a Judge'
        end
        
        redirect_to new_admin_setup_judge_path
    end

    def destroy
        @judge = User.find params[:id]
        @new_judge = Judge.find_by(user_id: @judge.id)
        
        @new_judge.destroy
        @judge.destroy
        
        flash[:notice] = "Judge #{@judge.name} deleted"
        redirect_to new_admin_setup_judge_path
    end
    
    def show
        puts "print!!"
        puts params
        
        
        redirect_to new_admin_setup_judge_path
    end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :bare_password)
  end

end

app/controllers/judge_controller.rb
class JudgeController < ApplicationController
    skip_before_action :require_login

    def index
        puts "hi user  #{current_user.id}"
        @judges = Judge.where(:user_id => current_user.id)
        @contests = []
        Contest.all.each do |c|
            @judges.each do |j|
                if c.id == j.contest_id
                    @contests << c
                end
            end
        end
        puts "contests: #{@contests}"
        @divisions = Division.all
    end

    def show
        @division = Division.find_by(:id => params[:id])
        @contest = Contest.find_by(:id => @division.contest_id)
        @judge = Judge.find_by(:user_id => current_user.id)
        @auctioneers = Auctioneer.where(:division_id => params[:id], :judge_id => @judge.id).uniq
        @users = []
        User.all.each do |user|
            @auctioneers.each do |auc|
                if user.id == auc.user_id
                    u = {}
                    u[:name] = user.name
                    u[:auc_id] = auc.id
                    u[:user_id] = user.id
                    u[:done] = auc.done
                    @users << u
                end
            end
        end
    end

    def edit
       @auc = Auctioneer.find_by(:id => params[:id])
       @user = User.find_by(:id => @auc.user_id)
       @div = Division.find_by(:id => @auc.division_id)
       @contest = Contest.find_by(:id => @div.contest_id)

       @qsheet = Qsheet.find_by(:id => @div.id)
       @qs = Question.where(:qsheet_id => @qsheet.id)
       @judge = Judge.find_by(:user_id => current_user.id)

       @scores = []
       @qs.each do |q|
        @scores << Scoresheet.where(:auctioneer_id => @auc.id, :question_id => q.id, :judge_id => @judge.id)
       end
    end

    def update
      puts "danguria #{params[:judges][:auc_id]}"
      done = true
      params['output'].keys.each do |id|
        score = Scoresheet.find_by(:id => id.to_i)
        puts "id; #{id}"
        score.score = params['output'][id][:score]
        q = Question.find_by(:id => score.question_id)
        if (score.score == "empty" || score.score == "0")
            puts "scoring is not finished"
           done = false 
        end
        if (q.dataType == "I")
          if score.score.is_a? Fixnum
              puts "this is not fixnum"
              done = false
          else
              puts "this is fixnum"
          end
        end
        score.save()
      end
      if done
        auc = Auctioneer.find_by(:id => params[:judges][:auc_id])
        auc.done = "true"
        auc.save
        flash[:success] = 'Auctioneer Judged Successfully'
      end

      redirect_to judge_index_path
    end
end

app/views/judge/edit.html.erb
<script>
    document.getElementById("judge-nav").className = "active";
</script>

<button type="button" class="btn btn-default btn-sm">
  <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> 
  <%= link_to 'Back to list', judge_index_path %>
</button>

<h2>Scoring <%= @user.name %></h2>
<h3>Contest: <%= @contest.contest_name %></h3>
<h3>Division: <%= @div.division_name %></h3>
<h3>Round: <%= @div.round %></h3>

<div id='scoresheet'>
<% qidx = 1 %>
<%= form_for :judges, :url =>  judge_path(current_user), :html => { :method => :put }  do |f| %>
  <%= f.hidden_field  :auc_id, :value => @auc.id %>
  <%#= render 'shared/errors', object: @scores%>
  <% @scores.each do |score| %>
  <% @qs.each do |q| %>
      <% if q.id == score[0].question_id && @auc.id == score[0].auctioneer_id %>
        <%= fields_for "output[]",score[0] do |score_fields| %>
        <div class="form-group">
          <label > Question <%= qidx %>(type: <%= q.dataType%> ): <%= q.content %></label>
          <% qidx = qidx + 1 %>
        </div>
        <div class="form-group">
          <%#= score_fields.text_field :score, class: 'form-control', required: true %>
          <% if q.dataType == "I" %>
            <%= score_fields.select :score, options_for_select((0..10).step(1).to_a.map{|s| ["#{s}", s]})%>
          <% elsif q.dataType == "S" %>
            <%= score_fields.text_field :score, class: 'form-control', required: true %>
          <% end %>

        </div>
        <%end%>
      <%end%>
  <% end %>
  <% end %>
    
  <div class="form-group"> 
    <input type="submit" value='Submit' class="btn btn-primary btn-med">
    <span id="helpBlock" class="help-block">Note that once you submit this page,
    you cannot view this page again!</span>
  </div>
<% end %>
</div>

app/views/judge/index.html.erb
<script>
    document.getElementById("judge-nav").className = "active";
</script>

<% @contests.each do |contest| %>
<br>
  <h2><%= contest.contest_name %> Contest </h2>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Division</th>
        <th>Round</th>
        <th>View Auctioneers</th>
      </tr>
    </thead>
    
    <tbody>
      <% @divisions.each do |division| %>
        <% if division.contest_id == contest.id %> 
          <tr>
            <td><%= division.division_name %></td>
            <td><%= division.round %></td>
            <td> <%= link_to 'See Auctioneers', judge_path(:id => division.id) %> </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/judge/score.html.erb
<script>
    document.getElementById("judge-nav").className = "active";
</script>

<button type="button" class="btn btn-default btn-sm">
  <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> 
  <%= link_to 'Back to list', judge_index_path %>
</button>

<h3>Scoring: <bold><%= User.find(@scoringAuc.user_id).name %> </bold></h3>
<h3><small>Contest: <%= @corrContest.contest_name %></small></h3>
<h3><small>Division: <%= Division.find(@scoringAuc.division_id).division_name %></small></h3>
<h3><small>Round: <%= Division.find(@scoringAuc.division_id).round %></small></h3>

<div id='scoresheet'>
<form class="form-horizontal">
  <% count = 1 %> 
  <% @questions.each do |question| %> 
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <%= question.content %>
      </label>
      <div class="col-sm-5">
        <input class="form-control">
      </div>
    </div>
    <% count += 1 %> 
  <% end %> 
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Submit</button>
      <span id="helpBlock" class="help-block">Note that once you submit,
      you come back to it again!</span>
    </div>
    
  </div>
  
  
</form>
</div>

app/views/judge/show.html.erb
<script>
    document.getElementById("judge-nav").className = "active";
</script>

<%= link_to(judge_index_path, :html => {:class => 'btn btn-default btn-med'}) do %>
<span class='glyphicon glyphicon-arrow-left'></span>
 Back to My Auctioneers
<% end %>

  <h2> Auctioneers of <%= @contest.contest_name%> Contest </h2>
  <h3> Division: <%= @division.division_name %></h3>
  <h3> Round: <%= @division.round %></h3>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th class="col-xs-6 col-sm-4">Name</th>
        <th class="col-xs-6 col-sm-4">Status</th>
      </tr>
    </thead>
    
    <tbody>
      <% @users.each do |user| %>
          <tr>
            <td><%= user[:name] %></td>
            <%if user[:done] == "false" %>
              <td> <%= link_to 'Score this auctioneer', edit_judge_path(:id => user[:auc_id]) %> </td>
            <%else %>
              <td> Judged </td>
            <%end%>
          </tr>
      <% end %>
    </tbody>
  </table>