config/routes.rb
Rails.application.routes.draw do
  resources :qsheets
=begin
  resources :users, only: [:new, :create] do
    member do
      get :activate
    end
  end
=end

  resources :reset_passwords, only: [:new, :create, :update, :edit]
  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin_setup do
    resources :contest, only: [:new, :create, :destroy, :edit, :show]
    resources :judge, only: [:new, :create, :destroy, :edit, :show]
    resources :auctioneer, only: [:new, :create, :destroy, :edit, :show]
    resources :question, only: [:new, :create, :destroy, :edit, :show]
  end
  get 'admin_setup' => 'admin_setup#setup'
  get 'admin_judge' => 'admin#judge'
  get 'admin_auctioneer' => 'admin#auctioneer'
  get 'admin_contest' => 'admin#contest'
  
  resources :admin, only: [:index, :judge, :auctioneer, :contest, :new, :create, :scoreSummary]
  resources :judge, only: [:index, :edit, :update, :show]

  get 'judge_score' => 'judge#score'
  get 'admin_scoreSummary' => 'admin#scoreSummary'
  
  get 'qsheets_show' => 'qsheets#show'

  
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out

  root to: 'main#index'

end

app/views/reset_passwords/edit.html.erb
<h1>Choose a new password</h1>

<%= form_for @user, url: reset_password_path(@token), method: :patch do |f| %>
  <%= render 'shared/errors', object: @user %>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control', required: true %>
  </div>

    <%= f.submit 'Set password', class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/reset_passwords/new.html.erb
<h1>Reset Password</h1>

<%= form_tag reset_passwords_path, method: :post do %>
  <div class="form-group">
    <%= label_tag :email %>
    <%= text_field_tag :email, nil, class: 'form-control', required: true %>
  </div>

  <%= submit_tag "Send reset instructions", class: 'btn btn-primary btn-lg' %>
<% end %>